import { db, questionsTable, roadSignsTable } from '../lib/db/src/index.ts';

async function seed() {
  console.log("🌱 Seeding database...");

  const questions = [
    {
      text: "When should you use your hooter in a built-up area?",
      options: ["To greet friends", "Only to avoid an accident", "To get people out of your way", "When you are angry"],
      correctAnswer: 1,
      category: "Rules",
      difficulty: "easy",
      explanation: "In built-up areas, the hooter should only be used as a warning to avoid a potential collision or accident.",
    },
    {
      text: "What is the general speed limit for a light motor vehicle on a wide tarred road in Zimbabwe?",
      options: ["80 km/h", "100 km/h", "120 km/h", "60 km/h"],
      correctAnswer: 2,
      category: "Rules",
      difficulty: "medium",
      explanation: "On wide tarred roads (highways), the general speed limit for light motor vehicles is 120 km/h unless otherwise stated.",
    },
    {
      text: "What does a solid white line in the middle of the road mean?",
      options: ["You may overtake", "Overtaking is permitted if clear", "You must not cross or straddle the line", "Parking is allowed"],
      correctAnswer: 2,
      category: "Road Markings",
      difficulty: "easy",
      explanation: "A solid white line indicates that you must not cross or straddle it, usually because it's dangerous to overtake there.",
    },
    {
      text: "At an uncontrolled intersection, who has the right of way?",
      options: ["The faster vehicle", "The vehicle on the right", "The vehicle on the left", "The larger vehicle"],
      correctAnswer: 1,
      category: "Intersections",
      difficulty: "medium",
      explanation: "In Zimbabwe, at an uncontrolled intersection, you must give way to traffic approaching from your right.",
    },
    {
      text: "When are you allowed to drive on the right-hand side of a road with two-way traffic?",
      options: ["When you are in a hurry", "To overtake when it is safe to do so", "Never", "When the road is empty"],
      correctAnswer: 1,
      category: "Rules",
      difficulty: "easy",
      explanation: "You may drive on the right side only for the purpose of overtaking, and only when it is safe and legal to do so.",
    },
    {
      text: "What is the meaning of a flashing red robot (traffic light)?",
      options: ["Proceed with caution", "Stop and then proceed when safe", "Stop and wait for it to turn green", "Yield to all traffic"],
      correctAnswer: 1,
      category: "Traffic Lights",
      difficulty: "medium",
      explanation: "A flashing red robot is treated like a four-way stop. You must stop completely and proceed only when it is safe.",
    },
    {
      text: "What should you do if your vehicle breaks down at night?",
      options: ["Leave it and walk for help", "Turn on hazard lights and place reflectors", "Wait inside until morning", "Set the car on fire"],
      correctAnswer: 1,
      category: "Emergency",
      difficulty: "easy",
      explanation: "You must use hazard lights and place warning triangles (reflectors) at least 30-50 meters behind and in front of the vehicle.",
    },
    {
      text: "How far from a corner are you allowed to park?",
      options: ["2 meters", "5 meters", "7.5 meters", "10 meters"],
      correctAnswer: 2,
      category: "Parking",
      difficulty: "hard",
      explanation: "Parking is generally prohibited within 7.5 meters of an intersection or corner.",
    },
    {
      text: "What is the 'Two-Second Rule' used for?",
      options: ["To cross an intersection", "To maintain a safe following distance", "To change gears", "To start the engine"],
      correctAnswer: 1,
      category: "General Rules",
      difficulty: "medium",
      explanation: "The two-second rule helps drivers maintain a safe distance between their car and the vehicle in front, regardless of speed.",
    },
    {
      text: "A continuous yellow line on the left side of the road means?",
      options: ["No parking allowed", "No stopping at any time", "Overtaking zone", "Emergency lane"],
      correctAnswer: 1,
      category: "Road Markings",
      difficulty: "medium",
      explanation: "A continuous yellow line on the edge of the road signifies that no stopping or parking is allowed at any time.",
    },
    {
      text: "What is the maximum speed limit in a built-up area (city/town)?",
      options: ["40 km/h", "60 km/h", "80 km/h", "100 km/h"],
      correctAnswer: 1,
      category: "Rules",
      difficulty: "easy",
      explanation: "The general speed limit in built-up areas is 60 km/h unless otherwise posted.",
    },
    {
      text: "What does a stationary green arrow on a traffic light mean?",
      options: ["Stop", "Yield", "Proceed in the direction of the arrow", "Wait for the main light to turn green"],
      correctAnswer: 2,
      category: "Traffic Lights",
      difficulty: "easy",
      explanation: "A green arrow means you may proceed in that direction, even if the main light is red.",
    },
    {
      text: "When meeting a vehicle at night with bright lights, you should?",
      options: ["Switch on your high beams", "Look slightly to the left edge of the road", "Close your eyes", "Stop immediately"],
      correctAnswer: 1,
      category: "Safety",
      difficulty: "medium",
      explanation: "To avoid being blinded, you should look toward the left edge of the road to guide your path.",
    },
    {
      text: "Which side must you overtake another vehicle on a standard road?",
      options: ["The right side", "The left side", "Either side", "The side with more space"],
      correctAnswer: 0,
      category: "Rules",
      difficulty: "easy",
      explanation: "In Zimbabwe, you must always overtake on the right side of the vehicle in front.",
    },
    {
      text: "What is the primary rule of the road in Zimbabwe?",
      options: ["Drive on the right", "Drive on the left", "Fastest car goes first", "Large vehicles have right of way"],
      correctAnswer: 1,
      category: "Rules",
      difficulty: "easy",
      explanation: "Zimbabwe follows the British system where vehicles drive on the left side of the road.",
    },
    {
      text: "A red triangle sign with its apex pointing down means?",
      options: ["Stop", "Yield / Give Way", "Danger", "No Entry"],
      correctAnswer: 1,
      category: "Signs",
      difficulty: "easy",
      explanation: "An inverted red triangle is the international symbol for 'Give Way'.",
    },
    {
      text: "When driving in heavy rain, you should?",
      options: ["Speed up to get home faster", "Turn on hazard lights and slow down", "Turn on headlights and increase following distance", "Stop in the middle of the road"],
      correctAnswer: 2,
      category: "Safety",
      difficulty: "medium",
      explanation: "Rain reduces visibility and traction. Using headlights and increasing distance helps prevent accidents.",
    },
    {
      text: "What is the legal blood alcohol limit for drivers in Zimbabwe?",
      options: ["0.00%", "0.05%", "0.08%", "0.10%"],
      correctAnswer: 2,
      category: "Legal",
      difficulty: "hard",
      explanation: "The legal limit is 0.08g per 100ml of blood.",
    },
    {
      text: "What does it mean if a policeman extends his arm horizontally toward you?",
      options: ["Proceed", "Slow down", "Stop", "Turn left"],
      correctAnswer: 2,
      category: "Signals",
      difficulty: "medium",
      explanation: "A policeman's arm held out horizontally means traffic approaching from that direction must stop.",
    },
    {
      text: "You may not overtake another vehicle when?",
      options: ["Approaching a blind rise or curve", "On a one-way street", "In a 60km/h zone", "The car in front is slow"],
      correctAnswer: 0,
      category: "Rules",
      difficulty: "easy",
      explanation: "Overtaking on a blind rise or curve is extremely dangerous as you cannot see oncoming traffic.",
    },
    {
      text: "A blue circular sign generally indicates?",
      options: ["Danger", "A prohibition", "A mandatory instruction", "General information"],
      correctAnswer: 2,
      category: "Signs",
      difficulty: "medium",
      explanation: "Blue circular signs are used for mandatory actions, such as 'Turn Left Only' or 'Bicycles Only'.",
    },
    {
      text: "What must you do at a 'Stop' sign if there is no other traffic?",
      options: ["Slow down and proceed", "Come to a complete stop", "Proceed at normal speed", "Flash your lights"],
      correctAnswer: 1,
      category: "Rules",
      difficulty: "easy",
      explanation: "A stop sign always requires a complete cessation of movement, regardless of traffic conditions.",
    },
    {
      text: "A broken white line on the road means?",
      options: ["No overtaking", "Overtaking permitted if safe", "Parking allowed", "One-way street only"],
      correctAnswer: 1,
      category: "Road Markings",
      difficulty: "easy",
      explanation: "Broken white lines indicate that you may cross them to overtake when it is safe to do so.",
    },
    {
      text: "When entering a roundabout, you must give way to?",
      options: ["Traffic from the left", "Traffic already in the roundabout (from the right)", "No one", "Pedestrians only"],
      correctAnswer: 1,
      category: "Intersections",
      difficulty: "medium",
      explanation: "Traffic entering a roundabout must yield to vehicles already circulating inside from the right.",
    },
    {
      text: "What is the minimum age to obtain a Class 4 driver's licence in Zimbabwe?",
      options: ["16 years", "17 years", "18 years", "21 years"],
      correctAnswer: 0,
      category: "Legal",
      difficulty: "medium",
      explanation: "In Zimbabwe, the minimum age for a Class 4 (light motor vehicle) licence is 16 years.",
    }
  ];

  const signs = [
    {
      name: "Stop Sign",
      category: "regulatory",
      meaning: "You must bring your vehicle to a complete stop and give way to all traffic.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Stop_sign.svg/1200px-Stop_sign.svg.png",
      usage: "Placed at intersections where a full stop is mandatory for safety.",
    },
    {
      name: "Give Way",
      category: "regulatory",
      meaning: "Slow down and prepare to stop to give way to traffic on the major road.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Yield_sign.svg/1200px-Yield_sign.svg.png",
      usage: "Commonly found at T-junctions or roundabouts.",
    },
    {
      name: "No Entry",
      category: "regulatory",
      meaning: "Vehicles are prohibited from entering this road.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/No_entry.svg/1200px-No_entry.svg.png",
      usage: "Used to prevent traffic from entering one-way streets in the wrong direction.",
    },
    {
      name: "Speed Limit 50",
      category: "regulatory",
      meaning: "Maximum speed allowed is 50 kilometers per hour.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Speed_limit_50.svg/1200px-Speed_limit_50.svg.png",
      usage: "Restricts speed in residential areas or specific zones.",
    },
    {
      name: "One Way",
      category: "regulatory",
      meaning: "Traffic is restricted to one direction only.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/South_Africa_road_sign_R103.svg/1200px-South_Africa_road_sign_R103.svg.png",
      usage: "Used on divided highways or narrow urban streets.",
    },
    {
      name: "Stop Here",
      category: "regulatory",
      meaning: "Mandatory stop at the line or sign location.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/South_Africa_road_sign_R1.1.svg/1200px-South_Africa_road_sign_R1.1.svg.png",
      usage: "Found at intersections where visibility is limited.",
    },
    {
      name: "No Overtaking",
      category: "regulatory",
      meaning: "You are not allowed to overtake other vehicles.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/No_overtaking.svg/1200px-No_overtaking.svg.png",
      usage: "Used in areas with poor visibility or narrow roads.",
    },
    {
      name: "No Automobiles",
      category: "regulatory",
      meaning: "Entry is prohibited for motor cars.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/South_Africa_road_sign_R201.svg/1200px-South_Africa_road_sign_R201.svg.png",
      usage: "Restricts access to pedestrian zones or specific lanes.",
    },
    {
      name: "No Trucks",
      category: "regulatory",
      meaning: "Entry is prohibited for heavy vehicles and trucks.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/South_Africa_road_sign_R202.svg/1200px-South_Africa_road_sign_R202.svg.png",
      usage: "Used to prevent heavy traffic on residential or weak roads.",
    },
    {
      name: "No Horn",
      category: "regulatory",
      meaning: "Do not use your vehicle's horn except in an emergency.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/South_Africa_road_sign_R218.svg/1200px-South_Africa_road_sign_R218.svg.png",
      usage: "Used near hospitals, schools, or quiet zones.",
    },
    {
      name: "Road Closed",
      category: "regulatory",
      meaning: "This road is completely closed to all traffic.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/South_Africa_road_sign_R201-B.svg/1200px-South_Africa_road_sign_R201-B.svg.png",
      usage: "Used for emergencies, events, or permanent closures.",
    },
    {
      name: "Parking",
      category: "information",
      meaning: "Permitted parking zone.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/South_Africa_road_sign_IN11.svg/1200px-South_Africa_road_sign_IN11.svg.png",
      usage: "Indicates where vehicles may be legally parked.",
    },
    {
      name: "No Parking",
      category: "regulatory",
      meaning: "Parking is not allowed in this area.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/South_Africa_road_sign_R216.svg/1200px-South_Africa_road_sign_R216.svg.png",
      usage: "Used to keep roads clear for traffic flow.",
    },
    {
      name: "No Left Turn",
      category: "regulatory",
      meaning: "Turning left is prohibited at this intersection.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/South_Africa_road_sign_R209.svg/1200px-South_Africa_road_sign_R209.svg.png",
      usage: "Used to manage traffic flow and prevent accidents.",
    },
    {
      name: "No Right Turn",
      category: "regulatory",
      meaning: "Turning right is prohibited at this intersection.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/South_Africa_road_sign_R210.svg/1200px-South_Africa_road_sign_R210.svg.png",
      usage: "Prevents crossing traffic in dangerous spots.",
    },
    {
      name: "No U-Turn",
      category: "regulatory",
      meaning: "U-turns are prohibited for all vehicles.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/South_Africa_road_sign_R213.svg/1200px-South_Africa_road_sign_R213.svg.png",
      usage: "Prevents dangerous maneuvers on busy roads.",
    },
    {
      name: "End of Speed Limit",
      category: "regulatory",
      meaning: "General speed limits apply from this point.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/South_Africa_road_sign_R102.svg/1200px-South_Africa_road_sign_R102.svg.png",
      usage: "Cancels specific speed restrictions previously posted.",
    },
    {
      name: "Overtaking Prohibited",
      category: "regulatory",
      meaning: "You may not pass other vehicles from this point.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/South_Africa_road_sign_R214.svg/1200px-South_Africa_road_sign_R214.svg.png",
      usage: "Found on narrow roads or areas with poor sightlines.",
    },
    {
      name: "Railway Crossing (Guarded)",
      category: "warning",
      meaning: "Level crossing with gates or barriers ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/South_Africa_road_sign_W310.svg/1200px-South_Africa_road_sign_W310.svg.png",
      usage: "Alerts drivers to stop when gates are closed.",
    },
    {
      name: "Railway Crossing (Unguarded)",
      category: "warning",
      meaning: "Level crossing without gates or barriers ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/South_Africa_road_sign_W311.svg/1200px-South_Africa_road_sign_W311.svg.png",
      usage: "Requires extra caution; look and listen for trains.",
    },
    {
      name: "Zebra Crossing",
      category: "warning",
      meaning: "Pedestrian crossing point ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/South_Africa_road_sign_W306.svg/1200px-South_Africa_road_sign_W306.svg.png",
      usage: "Drivers must be prepared to stop for pedestrians.",
    },
    {
      name: "School Ahead",
      category: "warning",
      meaning: "Children may be crossing the road near a school.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/South_Africa_road_sign_W308.svg/1200px-South_Africa_road_sign_W308.svg.png",
      usage: "Slow down and look out for children.",
    },
    {
      name: "Bus Zone",
      category: "warning",
      meaning: "Area where buses frequently enter or exit.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/South_Africa_road_sign_W309.svg/1200px-South_Africa_road_sign_W309.svg.png",
      usage: "Be aware of large vehicles and stopping passengers.",
    },
    {
      name: "Cycle Zone",
      category: "warning",
      meaning: "Cyclists frequent this area or lane.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/South_Africa_road_sign_W303.svg/1200px-South_Africa_road_sign_W303.svg.png",
      usage: "Look out for bicycles.",
    },
    {
      name: "Narrow Road Ahead",
      category: "warning",
      meaning: "The road narrows on both sides.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/South_Africa_road_sign_W202.svg/1200px-South_Africa_road_sign_W202.svg.png",
      usage: "Be cautious of narrowing path and oncoming traffic.",
    },
    {
      name: "Narrow Road (Left) Ahead",
      category: "warning",
      meaning: "The road narrows on the left side.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/South_Africa_road_sign_W203.svg/1200px-South_Africa_road_sign_W203.svg.png",
      usage: "Traffic on the left must merge or adjust.",
    },
    {
      name: "Narrow Road (Right) Ahead",
      category: "warning",
      meaning: "The road narrows on the right side.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/South_Africa_road_sign_W204.svg/1200px-South_Africa_road_sign_W204.svg.png",
      usage: "Traffic on the right must merge or adjust.",
    },
    {
      name: "Two-Way Traffic",
      category: "warning",
      meaning: "Traffic will be moving in both directions ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/South_Africa_road_sign_W212.svg/1200px-South_Africa_road_sign_W212.svg.png",
      usage: "Alerts drivers transitioning from one-way to two-way roads.",
    },
    {
      name: "Airport Ahead",
      category: "warning",
      meaning: "Road leads to or passes near an airport.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/South_Africa_road_sign_W327.svg/1200px-South_Africa_road_sign_W327.svg.png",
      usage: "Be aware of low-flying aircraft or sudden noise.",
    },
    {
      name: "Animal Zone",
      category: "warning",
      meaning: "Be alert for domestic animals crossing the road.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/South_Africa_road_sign_W301.svg/1200px-South_Africa_road_sign_W301.svg.png",
      usage: "Common in rural or farming areas.",
    },
    {
      name: "Right Zigzag Bend",
      category: "warning",
      meaning: "Series of curves ahead, starting to the right.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/South_Africa_road_sign_W106.svg/1200px-South_Africa_road_sign_W106.svg.png",
      usage: "Slow down for safe navigation of multiple bends.",
    },
    {
      name: "Left Zigzag Bend",
      category: "warning",
      meaning: "Series of curves ahead, starting to the left.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/South_Africa_road_sign_W105.svg/1200px-South_Africa_road_sign_W105.svg.png",
      usage: "Prepare for successive turns.",
    },
    {
      name: "Right Curve",
      category: "warning",
      meaning: "The road curves to the right ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/South_Africa_road_sign_W102.svg/1200px-South_Africa_road_sign_W102.svg.png",
      usage: "Slow down for a single right bend.",
    },
    {
      name: "Left Curve",
      category: "warning",
      meaning: "The road curves to the left ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/South_Africa_road_sign_W101.svg/1200px-South_Africa_road_sign_W101.svg.png",
      usage: "Slow down for a single left bend.",
    },
    {
      name: "Bumps",
      category: "warning",
      meaning: "There are two or more successive humps in the road.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/South_Africa_road_sign_W318.svg/1200px-South_Africa_road_sign_W318.svg.png",
      usage: "Slow down to avoid vehicle damage or loss of control.",
    },
    {
      name: "Speed-Breaker",
      category: "warning",
      meaning: "A single speed hump or plateau ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/South_Africa_road_sign_W332.svg/1200px-South_Africa_road_sign_W332.svg.png",
      usage: "Mandatory slow-down point.",
    },
    {
      name: "Men At Work",
      category: "warning",
      meaning: "Road maintenance or construction is taking place ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/South_Africa_road_sign_TW306.svg/1200px-South_Africa_road_sign_TW306.svg.png",
      usage: "Drivers must slow down and look for workers.",
    },
    {
      name: "Left Turn",
      category: "warning",
      meaning: "Intersection ahead where traffic can turn left.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/South_Africa_road_sign_W208.svg/1200px-South_Africa_road_sign_W208.svg.png",
      usage: "Alerts to turning traffic from the left side.",
    },
    {
      name: "Right Turn",
      category: "warning",
      meaning: "Intersection ahead where traffic can turn right.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/South_Africa_road_sign_W207.svg/1200px-South_Africa_road_sign_W207.svg.png",
      usage: "Alerts to turning traffic from the right side.",
    },
    {
      name: "Crossroads",
      category: "warning",
      meaning: "Intersection where two roads cross each other.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/South_Africa_road_sign_W201.svg/1200px-South_Africa_road_sign_W201.svg.png",
      usage: "Alerts to potential crossing traffic.",
    },
    {
      name: "Rough Road Ahead",
      category: "warning",
      meaning: "The road surface ahead is uneven or in poor condition.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/South_Africa_road_sign_W315.svg/1200px-South_Africa_road_sign_W315.svg.png",
      usage: "Drive slowly and carefully to avoid damage.",
    },
    {
      name: "Landslide Ahead",
      category: "warning",
      meaning: "Warning of possible falling rocks or debris.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/South_Africa_road_sign_W333.svg/1200px-South_Africa_road_sign_W333.svg.png",
      usage: "Common in mountainous or hilly areas.",
    },
    {
      name: "Hospital Ahead",
      category: "information",
      meaning: "Medical facility or hospital nearby.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/South_Africa_road_sign_IN1.svg/1200px-South_Africa_road_sign_IN1.svg.png",
      usage: "Be prepared for emergency vehicles and keep noise low.",
    },
    {
      name: "Steep Hill",
      category: "warning",
      meaning: "Warning of a steep descent or ascent.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/South_Africa_road_sign_W320.svg/1200px-South_Africa_road_sign_W320.svg.png",
      usage: "Check brakes and use appropriate gears.",
    },
    {
      name: "Narrow Bridge",
      category: "warning",
      meaning: "The bridge ahead is narrower than the road.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/South_Africa_road_sign_W213.svg/1200px-South_Africa_road_sign_W213.svg.png",
      usage: "Wait for oncoming traffic if the bridge is single-lane.",
    },
    {
      name: "U-Turn",
      category: "information",
      meaning: "Permitted U-turn area ahead.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/South_Africa_road_sign_IN10.svg/1200px-South_Africa_road_sign_IN10.svg.png",
      usage: "Indicates safe spots to reverse direction.",
    },
    {
      name: "Construction Zone",
      category: "warning",
      meaning: "Area under active construction.",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/South_Africa_road_sign_TW301.svg/1200px-South_Africa_road_sign_TW301.svg.png",
      usage: "Watch for machinery and changing road layouts.",
    }
  ];

  try {
    console.log("Clearing existing data...");
    await db.delete(questionsTable);
    await db.delete(roadSignsTable);

    console.log("Inserting questions...");
    for (const q of questions) {
      await db.insert(questionsTable).values(q);
    }

    console.log("Inserting signs...");
    for (const s of signs) {
      await db.insert(roadSignsTable).values(s);
    }

    console.log("✅ Seeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error);
    process.exit(1);
  }
}

seed();
